### ISSUE TITLE
Unexpected evaluation output

### ISSUE THREAD

**Issue by Fangtangtang** [Jikai0Wang/OPT-Tree#2]
Hi, I tried to evaluate using `evaluation.eval_opt_classic` and found the output weird.
I evaluated with `python -m evaluation.eval_opt_classic \
                 --draft-model-path JackFram/llama-68m \
                 --base-model-path sharpbai/Llama-2-7b-hf \
                 --bench-name mt_bench \
                 --answer-file ./mt_classic_opt.jsonl \
                 --temperature 0 \
                 --nodes 60 \
                 --threshold 0.5 \
                 --max_depth 10` and print verified `best_candidate` in `spforward`. Then I found that the best candidate is always [13]. 

`print` added in the blue box.
<img width="769" alt="image" src="https://github.com/user-attachments/assets/5aeb05ea-41b7-4d2d-925a-f7b41589fa68">

<img width="154" alt="image" src="https://github.com/user-attachments/assets/7488258d-0d64-4b7a-a6aa-28a74fbb5977">

**Comment by Jikai0Wang** [comment]
Can you provide the sample of this happening? We re-ran the program and the results for the first sample in mt bench are shown below:
![image](https://github.com/user-attachments/assets/5513b80c-1a55-4702-9df7-71870bde6dd9)

**Comment by Fangtangtang** [comment]
I did not make change to the rest of the code and use `python -m evaluation.eval_opt_classic \                                    
                 --draft-model-path JackFram/llama-68m \
                 --base-model-path sharpbai/Llama-2-7b-hf \
                 --bench-name mt_bench \
                 --answer-file ./mt_classic_opt.jsonl \
                 --temperature 0 \
                 --nodes 60 \
                 --threshold 0.5 \
                 --max_depth 10`. 
I couldn't use `meta-llama/Llama-2-7b-chat-hf` due to authorization issues, so I used `sharpbai/Llama-2-7b-hf` as the base model instead, would that be a problem?
<img width="200" alt="image" src="https://github.com/user-attachments/assets/7dac0802-c680-437d-949d-ebec045c574f">

**Comment by Jikai0Wang** [comment]
I downloaded this version of llama and found that it always outputs 13 for any input when using model.generate(). I'm guessing this might be due to errors in the model parameters, or it not being loaded correctly via the from_pretrained() method. Please try another version of Llama-2-7b-chat-hf.

**Comment by Fangtangtang** [comment]
That’s weird, it works in other experiments. Also, it works fine under certain conditions when using different datasets.😶‍🌫️
![屏幕截图 2024-08-10 224713](https://github.com/user-attachments/assets/77a1f325-cac4-4d16-b514-524ac0a5956b)

Anyway, thanks a lot for your time.
